# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVFoundation_Audio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVFoundation_Audio

pod "youtube-ios-player-helper", "~> 1.0.3"

end
